# Gruvbox Dark
$bg = rgb(282828)
$bg1 = rgb(3c3836)
$bg2 = rgb(504945)
$fg = rgb(ebdbb2)
$red = rgb(cc241d)
$green = rgb(98971a)
$yellow = rgb(d79921)
$blue = rgb(458588)
$purple = rgb(b16286)
$aqua = rgb(689d6a)
$orange = rgb(d65d0e)
$active_border = rgb(d79921) rgb(d65d0e) 45deg
$inactive_border = rgb(3c3836)
$waybar_bg = rgba(40, 40, 40, 0.9)
$waybar_border = rgba(215, 153, 33, 0.5)
$waybar_fg = #ebdbb2
$waybar_accent = #d79921
$waybar_red = #cc241d
$waybar_green = #98971a
$waybar_blue = #458588
$waybar_purple = #b16286
$waybar_aqua = #689d6a
$waybar_orange = #d65d0e
$waybar_gray = #928374
$ghostty_theme = GruvboxDark
$nvim_background = dark
$nvim_colorscheme = gruvbox
