# Gruvbox Light
$bg = rgb(fbf1c7)
$bg1 = rgb(ebdbb2)
$bg2 = rgb(d5c4a1)
$fg = rgb(3c3836)
$red = rgb(cc241d)
$green = rgb(79740e)
$yellow = rgb(b57614)
$blue = rgb(076678)
$purple = rgb(8f3f71)
$aqua = rgb(427b58)
$orange = rgb(af3a03)
$active_border = rgb(b57614) rgb(af3a03) 45deg
$inactive_border = rgb(d5c4a1)
$waybar_bg = rgba(251, 241, 199, 0.9)
$waybar_border = rgba(181, 118, 20, 0.5)
$waybar_fg = #3c3836
$waybar_accent = #b57614
$waybar_red = #cc241d
$waybar_green = #79740e
$waybar_blue = #076678
$waybar_purple = #8f3f71
$waybar_aqua = #427b58
$waybar_orange = #af3a03
$waybar_gray = #7c6f64
$ghostty_theme = GruvboxLight
$nvim_background = light
$nvim_colorscheme = gruvbox
