# This file should be auto-generated by nixos-generate-config.
# Run: nixos-generate-config --show-hardware-config > hosts/adam/hardware-configuration.nix
{ config, lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # TODO: Replace with your actual hardware configuration.
  # Generate it on the target machine with:
  #   nixos-generate-config --show-hardware-config
  boot.initrd.availableKernelModules = [ ];
  boot.kernelModules = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };
}
