general {
    lock_cmd = qs ipc call shell lock
    before_sleep_cmd = qs ipc call shell lock
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

listener {
    timeout = 300 # 5 minutes - lock screen
    on-timeout = qs ipc call shell lock
}

listener {
    timeout = 360 # 6 minutes - turn off display
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1800 # 30 minutes - suspend
    on-timeout = systemctl suspend
}
